---

matrix:
  include:
    - os: osx
      env: PYTHON_VERSION=2.7
    - os: trusty
      env: PYTHON_VERSION=2.7

install:
  - pyenv install "${PYTHON_VERSION}-dev"
  - pyenv global "${PYTHON_VERSION}-dev"
  - pip install mock coverage ipdb ipython pytest pre-commit autopep8 flake8

script:
  - coverage run --source=bin/ --omit=bin/autojump_argparse.py -m py.test -vv -rxs --tb native -s --strict
  - coverage report -m
