---

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7
      install:
        - pyenv install "${PYTHON_VERSION}-dev"
        - pyenv global "${PYTHON_VERSION}-dev"
    - python: "2.7"
      install:
        - pip install virtualenv
    - os: windows
      language: shell
      install:
        - choco install -y python2
        - env
        - ls -la /
        # - /C/Python27/Scripts/pip.exe install virtualenv
script:
  - env
  - pip install virtualenv virtualenvwrapper
  - source "$(which virtualenv.sh)"
  - mkvirtualenv autojump
  - pip install mock coverage ipdb ipython pytest pre-commit autopep8 flake8
  - coverage run --source=bin/ --omit=bin/autojump_argparse.py -m py.test -vv -rxs --tb native -s --strict
  - coverage report -m
