---

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7
      install:
        - pyenv install "${PYTHON_VERSION}-dev"
        - pyenv global "${PYTHON_VERSION}-dev"
        - pip install mock coverage ipdb ipython pytest pre-commit autopep8 flake8
    - os: trusty
      python: "2.7"
      install:
        - pip install mock coverage ipdb ipython pytest pre-commit autopep8 flake8
    - os: windows
      language: shell
      install:
        - choco install -y python2
        - C:\Python27\Scripts\pip.exe install virtualenv

script:
  - coverage run --source=bin/ --omit=bin/autojump_argparse.py -m py.test -vv -rxs --tb native -s --strict
  - coverage report -m
